config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  resources :documents
  root "home#index"
  get 'logedin', to: 'home#logedin'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'home#logedin'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'home#logedin', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'emprunter', to:'documents#emprunter'
  #get 'search', to: 'materiels#search' 
  get 'search', to: 'documents#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/document.rb
class Document < ApplicationRecord
   # belongs_to :adherent
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all

    #CSV
    # respond_to do |format|
    #   format.html
    #   format.csv{send_data @documents.to_csv} 
  end

  #chercher un doc
  def search
    @documents = Document.where("titre LIKE ?", "%" + params[:q] + "%")
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #-----------------------------------------------------------------------------------
  # Emprunter
  # def emprunter
  #   @documents = Document.where(document_id: @document.id
  # end

  #csv
  # def self.to_csv
  #   attributes = %w{id titre genre}

  #   CSV.generate(headers: true) do |csv|
  #     csv << attributes

  #     all.each do |document|
  #       csv << document.attributes.values_at(*attributes)
  #     end
  #   end
  # end
  #-------------------------------------------------------------------------------


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:titre, :genre)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Titre:</strong>
    <%= document.titre %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= document.genre %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titre, style: "display: block" %>
    <%= form.text_area :titre %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.select :genre, ['Livre', 'volume', 'BD', 'Revue', 'Dictionnaire'] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/emprunter.html.erb
<h1>La liste des elements empruntés </h1>

<!--
<div id="documents">
    <table class="table table-dark table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Titre</th>
          <th scope="col">Genre</th>
          <th scope="col">Affichage</th>
          <th scope="col">Modification</th>
          <th scope="col">Suppression</th>
          <th scope="col">Emprunte</th>
        </tr>
      </thead>
      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <th scope="row"><%= document.id %></th>
            <td><%= document.titre %></td>
            <td><%= document.genre %></td>
            <td><%= link_to "Afficher", document, class:"btn btn-success" %></td>
            <td><%= link_to "Modifier", edit_document_path(document), class:"btn btn-secondary" %></td>
            <td><%= button_to "Rendre", @document, method: :delete, class:"btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
</div>
-->

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>La liste des documents créés </h1>

<div id="documents">
    <table class="table table-dark table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Titre</th>
          <th scope="col">Genre</th>
          <th scope="col">Affichage</th>
          <th scope="col">Modification</th>
          <th scope="col">Suppression</th>
          <th scope="col">Emprunte</th>
        </tr>
      </thead>
      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <th scope="row"><%= document.id %></th>
            <td><%= document.titre %></td>
            <td><%= document.genre %></td>
            <td><%= link_to "Afficher", document, class:"btn btn-success" %></td>
            <td><%= link_to "Modifier", edit_document_path(document), class:"btn btn-secondary" %></td>
            <td><%= button_to "Supprimer", @document, method: :delete, class:"btn btn-danger" %></td>
            <!--<td><%= link_to "Emprunter", emprunter_path(document), class:"btn btn-outline-warning" %></td>-->

            <td><%= button_to "Emprunter", @document, method: :emprunter, class:"btn btn-outline-warning" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
</div>

<%= link_to "New document", new_document_path, class:"btn btn-primary" %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/search.html.erb
    <h1 class="text-center">Vous cherchez l'un de ces éléments?</h1>

    <%= render @documents %>

    <div>
    <%= link_to "Back to documents", documents_path %>
  
    <%= button_to "Destroy this document", @document, method: :delete %>
  </div>
  

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>