config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  resources :documents
  root "home#index"
  get 'logedin', to: 'home#logedin'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'home#logedin'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'home#logedin', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'emprunter', to:'documents#emprunter'
  #get 'search', to: 'materiels#search' 
  get 'search', to: 'documents#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/materiel.rb
class Materiel < ApplicationRecord
end

app/controllers/materiels_controller.rb
class MaterielsController < ApplicationController
  before_action :set_materiel, only: %i[ show edit update destroy ]

  # GET /materiels or /materiels.json
  def index
    @materiels = Materiel.all
  end

  #chercher un matériel
  def search
    @materiels = Materiel.where("name LIKE ?", "%" + params[:q] + "%")
  end

  # GET /materiels/1 or /materiels/1.json
  def show
  end

  # GET /materiels/new
  def new
    @materiel = Materiel.new
  end

  # GET /materiels/1/edit
  def edit
  end

  # POST /materiels or /materiels.json
  def create
    @materiel = Materiel.new(materiel_params)

    respond_to do |format|
      if @materiel.save
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully created." }
        format.json { render :show, status: :created, location: @materiel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materiels/1 or /materiels/1.json
  def update
    respond_to do |format|
      if @materiel.update(materiel_params)
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully updated." }
        format.json { render :show, status: :ok, location: @materiel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materiels/1 or /materiels/1.json
  def destroy
    @materiel.destroy

    respond_to do |format|
      format.html { redirect_to materiels_url, notice: "Materiel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materiel
      @materiel = Materiel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def materiel_params
      params.require(:materiel).permit(:name, :disponibilte, :etat)
    end
end

app/helpers/materiels_helper.rb
module MaterielsHelper
end

app/views/materiels/_form.html.erb
<%= form_with(model: materiel) do |form| %>
  <% if materiel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(materiel.errors.count, "error") %> prohibited this materiel from being saved:</h2>

      <ul>
        <% materiel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :disponibilte, style: "display: block", class:"form-label" %>
    <%= form.select :disponibilte, ['disponible', 'non disponible'], class:"btn btn-primary" %>
  </div>

  <div class="mb-3">
    <%= form.label :etat, style: "display: block", class:"form-label" %>
    <%= form.select :etat, ['marche', 'en panne'], class:"form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/materiels/_materiel.html.erb
<div id="<%= dom_id materiel %>">
  <p>
    <strong>Name:</strong>
    <%= materiel.name %>
  </p>

  <p>
    <strong>Disponibilte:</strong>
    <%= materiel.disponibilte %>
  </p>

  <p>
    <strong>Etat:</strong>
    <%= materiel.etat %>
  </p>

</div>

app/views/materiels/edit.html.erb
<h1>Editing materiel</h1>

<%= render "form", materiel: @materiel %>

<br>

<div>
  <%= link_to "Show this materiel", @materiel %> |
  <%= link_to "Back to materiels", materiels_path %>
</div>

app/views/materiels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Les materiels créés</h1>
<p>On a que les PCs maintenant</p>

<div id="materiels">
  <table class="table table-dark table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nom</th>
        <th scope="col">Disponibilte</th>
        <th scope="col">Etat</th>
        <th scope="col">Affichage</th>
        <th scope="col">Modification</th>
        <th scope="col">Suppression</th>
        <th scope="col">Emprunte</th>
      </tr>
    </thead>
    <tbody>
    <% @materiels.each do |materiel| %>
        <tr>
          <th scope="row"><%= materiel.id %></th>
          <td><%= materiel.name %></td>
          <td><%= materiel.disponibilte %></td>
          <td><%= materiel.etat %></td>
          <td><%= link_to "Afficher", materiel, class:"btn btn-success" %></td>
          <td><%= link_to "Modifier", edit_materiel_path(materiel), class:"btn btn-secondary" %></td>
          <td><%= button_to "Supprimer", @materiel, method: :delete, class:"btn btn-danger" %></td>
          <td><%= button_to "Emprunter", @materiel, class:"btn btn-outline-warning" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New materiel", new_materiel_path, class:"btn btn-primary"  %>

app/views/materiels/new.html.erb
<h1>New materiel</h1>

<%= render "form", materiel: @materiel %>

<br>

<div>
  <%= link_to "Back to materiels", materiels_path %>
</div>

app/views/materiels/search.html.erb
    <h1 class="text-center">Vous cherchez l'un de ces éléments?</h1>

    <%= render @materiels %>

app/views/materiels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @materiel %>

<div>
  <%= link_to "Edit this materiel", edit_materiel_path(@materiel) %> |
  <%= link_to "Back to materiels", materiels_path %>

  <%= button_to "Destroy this materiel", @materiel, method: :delete %>
</div>